steps:
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'simon-ps-consolidator'
      - '--image'
      - 'us-east5-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/simon-ps-agent/simon-ps-consolidator:$COMMIT_SHA'
      - '--region'
      - 'us-east4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_ENTRYPOINT=main'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '120'
