steps:
  # Deploy to Cloud Run using the buildpack image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'simon-ps-consolidator'
      - '--source=.'
      - '--region=us-east4'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_ENTRYPOINT=consolidate_ps'
